version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: library_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  bookservice:
    build:
      context: ./BookService
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: library_db
    ports:
      - "8080:8080"

volumes:
  pg_data:
